# Generated by Django 3.1.3 on 2021-09-27 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='city',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
