# Generated by Django 3.1.3 on 2021-09-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_auto_20210927_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='user',
        ),
    ]
