# Generated by Django 3.1.3 on 2021-09-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_remove_city_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather_app.userip'),
        ),
    ]
