# Generated by Django 3.1.3 on 2021-09-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0004_city_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather_app.userip'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
