# Generated by Django 3.1.3 on 2021-09-27 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0005_auto_20210927_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('text', models.CharField(max_length=1200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
